name: Base Image
on:
  workflow_dispatch:

jobs:

  base:
    runs-on: ubuntu-latest
    name: Build, Tag & Push Image
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      name: Login to GitHub Container Registry
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: |
        docker build -f Dockerfile.base -t ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')-base:${{ github.sha }} .
    - name: Tag image
      run: |
        docker tag ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')-base:${{ github.sha }} ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')-base:latest

    - name: Push image
      run: |
        docker push ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')-base:${{ github.sha }}
        docker push ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')-base:latest
