name: SteamCMD Image
on:
  workflow_dispatch:
  schedule:
  - cron: "0 3 * * 1"

jobs:
  steamcmd:
    runs-on: ubuntu-latest
    name: Build, Tag & Push Image
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      name: Login to GitHub Container Registry
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Build image
      run: |
        docker build -f Dockerfile -t ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):${{ github.sha }} .

    - name: Tag image
      run: |
        docker build -f Dockerfile -t ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):${{ github.sha }} .
        docker tag ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):${{ github.sha }} ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):latest

    - name: Push image
      run: |
        docker push ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):${{ github.sha }}
        docker push ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):latest
